# Generated by Django 6.0.5 on 2026-06-02 05:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('project_name', models.CharField(max_length=120)),
                ('milestone_name', models.CharField(max_length=120)),
                ('task_name', models.CharField(max_length=160)),
                ('task_type', models.CharField(choices=[('Development', 'Development'), ('Bug Fix', 'Bug Fix'), ('Testing', 'Testing'), ('Research', 'Research'), ('Documentation', 'Documentation'), ('Meeting', 'Meeting'), ('Support', 'Support'), ('Code Review', 'Code Review')], max_length=30)),
                ('planned_start', models.TimeField()),
                ('planned_end', models.TimeField()),
                ('actual_start', models.TimeField()),
                ('actual_end', models.TimeField()),
                ('planned_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('remarks', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='accounts.employee')),
            ],
            options={
                'ordering': ['actual_start', 'created_at'],
                'indexes': [models.Index(fields=['employee', 'date'], name='timesheets__employe_662a75_idx')],
            },
        ),
    ]
