# Generated by Django 6.0.5 on 2026-06-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='review_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=12),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
