# Generated by Django 6.0.5 on 2026-06-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_accounts_em_role_9455c0_idx_and_more'),
        ('timesheets', '0002_timesheet_review_comments_timesheet_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ['-date', 'actual_start']},
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['employee', 'status', 'date'], name='timesheets__employe_292811_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['status', 'date'], name='timesheets__status_b6eea6_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['project_name'], name='timesheets__project_ad818f_idx'),
        ),
    ]
