# Generated by Django 6.0.5 on 2026-06-08 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='timesheets.project')),
            ],
            options={
                'ordering': ['project__name', 'name'],
                'indexes': [models.Index(fields=['project', 'is_active'], name='timesheets__project_c88bc7_idx')],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
