# Generated by Django 6.0.5 on 2026-06-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0007_normalize_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start_time', models.TimeField(default='06:00:00')),
                ('planned_end_time', models.TimeField(default='12:00:00')),
                ('actual_start_time', models.TimeField(default='12:00:00')),
                ('actual_end_time', models.TimeField(default='23:59:00')),
                ('daily_target_hours', models.IntegerField(default=8)),
                ('weekly_target_hours', models.IntegerField(default=40)),
                ('allow_overlap', models.BooleanField(default=False)),
                ('require_milestone', models.BooleanField(default=False)),
                ('task_types', models.TextField(default='Development,Bug Fix,Testing,Research,Documentation,Meeting,Support,Code Review')),
            ],
        ),
        migrations.RenameIndex(
            model_name='dailyreport',
            new_name='timesheets__employe_d784dd_idx',
            old_name='timesheets__employe_8c41ca_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyreport',
            new_name='timesheets__status_19e523_idx',
            old_name='timesheets__status_a42d8d_idx',
        ),
        migrations.RenameIndex(
            model_name='timesheet',
            new_name='timesheets__daily_r_ba3202_idx',
            old_name='timesheets__daily_r_ec1d55_idx',
        ),
        migrations.RenameIndex(
            model_name='timesheet',
            new_name='timesheets__project_34a5c7_idx',
            old_name='timesheets__project_63f736_idx',
        ),
    ]
