# Generated by Django 6.0.5 on 2026-06-11 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0008_systemsetting_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'verbose_name': 'System Setting'},
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='allow_overlap',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='daily_target_hours',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='require_milestone',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='task_types',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='weekly_target_hours',
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='actual_end_time',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='actual_start_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='planned_end_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='planned_start_time',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
    ]
