# Generated by Django 6.0.5 on 2026-06-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0009_timesheet_window_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start_time', models.TimeField(default='06:00:00')),
                ('planned_end_time', models.TimeField(default='12:00:00')),
                ('actual_start_time', models.TimeField(default='12:00:00')),
                ('actual_end_time', models.TimeField(default='23:59:00')),
            ],
        ),
        migrations.DeleteModel(
            name='SystemSetting',
        ),
    ]
