# Generated by Django 6.0.5 on 2026-06-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0010_timesheetsetting_delete_systemsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='actual_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='actual_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='planned_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='planned_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
